stages:
  - build
  - test
  - weekly_tests
  - publish
  - docs

lint:
  image: python:3.7-buster
  stage: build
  script:
    - python -m pip install --upgrade pip
    - pip install flake8
    - flake8 eoreader
  tags:
    - linux
  except:
    changes:
      - "*.html"
      - docs/*

pytest:
  image: docker.sertit.unistra.fr/extracteo/extracteo_deps:latest
  stage: test
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt --ignore-installed PyYAML
    - pip install -e .
  script:
    - pytest -v --durations=0 --cov-report term --cov-report xml:cov.xml --cov=eoreader CI/SCRIPTS
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  tags:
    - linux
  except:
    changes:
      - "*.html"
      - docs/*

tox-linux:on-schedule:
  image: docker.sertit.unistra.fr/extracteo/extracteo_deps:latest
  stage: weekly_tests
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt --ignore-installed PyYAML
    - pip install -e .
  script:
    - tox -c tox.ini
  tags:
    - linux

tox-windows:on-schedule:
  stage: weekly_tests
  before_script:
    - conda init
    - conda env create -f environment.yml
    - source ~/.bashrc  # <- !!!
    - export PYTHONPATH="$PYTHONPATH:."
    - conda activate eoreader
  script:
    - tox -c tox-conda.ini
  tags:
    - windows


upload_wheel:linux:
  image: python:3.7-buster
  stage: publish
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${PYPI_PWD} TWINE_USERNAME=${PYPI_TOKEN} python -m twine upload dist/*
  tags:
    - linux
  only:
    - tags

pages:
  image: docker.sertit.unistra.fr/extracteo/extracteo_deps:latest
  stage: docs
  script:
    - python -m pip install --upgrade pip
    - pip install -r requirements-doc.txt --ignore-installed PyYAML
    - sphinx-build docs/ docs/_build/html/
    - mv docs/_build/html/ public/
  artifacts:
    paths:
      - public
  tags:
    - linux
  only:
    - master
